export const dummyApprovalsPost = {
  uid: 1,
  userAvatar: require('../../assets/users/Donn.png'),
  approved: false,
  likes: 4,
  title: 'Redux is hard',
  text: 'I use these reference docs all the time. I hope somebody can find them usefull',
  category: 'Mobile Development',
  timestamp: '4.26.2023',
  tags: ['why', 'redux', 'help-me'],
  links: [
    {
      title: 'redux',
      url: 'https://redux.js.org/',
    },
  ],
  comments: [
    {
      name: 'Brandon',
      text: 'Nemo, enim ipsam voluptatem quia voluptas sit',
    },
    {
      name: 'Mev',
      text: 'quis nostrum exercitationem ullam corporis suscipit!',
    },
  ],
};

export const dummyApprovalsFeed = [
  {
    uid: 2,
    id: 1,
    name: 'brawoods',
    approved: false,
    userAvatar: require('../../assets/users/Brandon.png'),
    likes: 4,
    title: 'Redux is hard',
    link: 'https://redux.js.org/',
    text: 'I remember how long it took me to really get used to Redux. Here is an awesome guide that I found really usefull at the newb stage',
    category: 'Mobile Development',
    timestamp: '4.26.2023',
    tags: ['why', 'redux', 'help me'],
    links: [
      {
        title: 'redux',
        url: 'https://redux.js.org/',
      },
    ],
    comments: [
      {
        name: 'Brandon',
        text: 'Nemo, enim ipsam voluptatem quia voluptas sit',
      },
      {
        name: 'Mev',
        text: 'quis nostrum exercitationem ullam corporis suscipit!',
      },
    ],
  },
  {
    uid: 3,
    id: 2,
    name: 'Jenessap',
    approved: false,
    userAvatar: require('../../assets/users/Jenessa.png'),
    likes: 2,
    title: 'When is Date() getting updated?',
    text: 'I heard Temporal() is coming at some point. Does anyone know what the difference will be?',
    link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now',
    category: 'Coding',
    timestamp: '4.24.2023',
    tags: ['in', 'another', 'world'],
    comments: [
      {
        name: 'Majd',
        text: 'Excepteur sint occaecat cupidatat non proident',
      },
      {
        name: 'Janessa',
        text: 'deserunt mollit anim id est laborum.',
      },
    ],
  },
  {
    uid: 4,
    id: 3,
    name: 'kylestevens32',
    approved: false,
    userAvatar: require('../../assets/users/Kyle.png'),
    likes: 1,
    title: 'Is this a good set?',
    link: 'https://www.meta.com/quest/quest-pro/tech-specs/#tech-specs',
    text: "I don't want to overpay for my first set. Can anyone point me in the right direction for a comparison guide?",
    category: 'Virtual Reality',
    timestamp: '4.26.2023',
    tags: ['cool', 'tech', 'crazy'],
    comments: [
      {
        name: 'Nam',
        text: 'Duis aute irure dolor in reprehenderit',
      },
      {
        name: 'Donn',
        text: 'ut labore et dolore magna aliqua',
      },
    ],
  },
  {
    uid: 5,
    id: 4,
    name: 'MSCS22',
    approved: false,
    userAvatar: require('../../assets/users/Majd.png'),
    likes: 0,
    title: 'Imagine what comes next...',
    text: 'These image models are getting crazy. This is so cool!',
    link: 'https://www.nature.com/articles/s41598-023-33614-0',
    category: 'Machine Learning',
    timestamp: '4.26.2023',
    tags: ['M-L', 'science', 'tech-for-good'],
    comments: [],
  },
  {
    uid: 6,
    id: 5,
    name: 'mevcaus',
    approved: false,
    userAvatar: require('../../assets/users/Mev.png'),
    likes: 3,
    title: 'Do you eat pizza with fruit?',
    text: "I mean, tomatos, of course, but, like real fruit? that's not right. Here is a list of other foods that have no business being near fruit: 1. sandwiches, 2. open-faced sandwiches, 3. wraps that you can get at a sandwich store..",
    category: 'Virtual Reality',
    timestamp: '4.26.2023',
    tags: ['k-logs', 'C++', 'python'],
    comments: [],
  },
  {
    uid: 7,
    id: 6,
    name: 'nnguye47',
    approved: false,
    userAvatar: require('../../assets/users/Nam.png'),
    likes: 3,
    title: 'Have any of you been to the Metaverse?',
    text: 'I wonder if it will ever take off? ',
    link: 'https://www.wired.com/story/what-is-the-metaverse/',
    category: 'Virtual Reality',
    timestamp: '4.26.2023',
    tags: ['cool', 'tech', 'fun', 'social-media'],
    comments: [],
  },
  {
    uid: 8,
    id: 7,
    name: 'mevcaus',
    approved: false,
    userAvatar: require('../../assets/users/Mev.png'),
    likes: 4,
    title: 'Just built an API',
    text: 'Here is a cool API I just built. Please let me know what you think',
    link: 'https://github.com/StackageApp/stackage-server',
    category: 'Coding',
    timestamp: '4.26.2023',
    tags: ['javascript', 'Expressjs', 'node.js', 'firebase'],
    comments: [],
  },
  {
    uid: 8,
    id: 8,
    name: 'ForeDaddy',
    approved: false,
    userAvatar: require('../../assets/users/Donn.png'),
    likes: 4,
    title: 'Salary Data Website',
    text: 'This site provides a ton of cool salary info in the tech sphere. I think it would be cool if everybody was more comfortable with posting their own data so we can all see what we are worth',
    link: 'https://www.levels.fyi/?compare=Google,Facebook,Microsoft&track=Software%20Engineer',
    category: 'Tech Jobs',
    timestamp: '4.26.2023',
    tags: ['cool', 'tech', 'jobs'],
    comments: [],
  },
];
