export const dummyApprovalsPost = {
  uid: 1,
  userAvatar: require('../../assets/users/Donn.png'),
  approved: false,
  likes: 4,
  title: 'Redux is hard',
  text: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem',
  category: 'Mobile Development',
  timestamp: '4.26.2023',
  tags: ['why', 'redux', 'help me'],
  links: [
    {
      title: 'redux',
      url: 'https://redux.js.org/',
    },
  ],
  comments: [
    {
      name: 'Brandon',
      text: 'Nemo, enim ipsam voluptatem quia voluptas sit',
    },
    {
      name: 'Mev',
      text: 'quis nostrum exercitationem ullam corporis suscipit!',
    },
  ],
};

export const dummyApprovalsFeed = [
  {
    uid: 2,
    id: 1,
    name: 'brawoods',
    approved: false,
    userAvatar: require('../../assets/users/Brandon.png'),
    likes: 4,
    title: 'Redux is hard',
    text: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem',
    category: 'Mobile Development',
    timestamp: '4.26.2023',
    tags: ['why', 'redux', 'help me'],
    links: [
      {
        title: 'redux',
        url: 'https://redux.js.org/',
      },
    ],
    comments: [
      {
        name: 'Brandon',
        text: 'Nemo, enim ipsam voluptatem quia voluptas sit',
      },
      {
        name: 'Mev',
        text: 'quis nostrum exercitationem ullam corporis suscipit!',
      },
    ],
  },
  {
    uid: 3,
    id: 2,
    name: 'Jenessap',
    approved: false,
    userAvatar: require('../../assets/users/Jenessa.png'),
    likes: 2,
    title: 'minim veniam',
    text: 'in voluptate velit esse cillum dolore',
    category: 'Virtual Reality',
    timestamp: '4.24.2023',
    tags: ['in', 'another', 'world'],
    comments: [
      {
        name: 'Majd',
        text: 'Excepteur sint occaecat cupidatat non proident',
      },
      {
        name: 'Janessa',
        text: 'deserunt mollit anim id est laborum.',
      },
    ],
  },
  {
    uid: 4,
    id: 3,
    name: 'kylestevens32',
    approved: false,
    userAvatar: require('../../assets/users/Kyle.png'),
    likes: 1,
    title: 'Lorem',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    category: 'Virtual Reality',
    timestamp: '4.26.2023',
    tags: ['cool', 'tech', 'crazy'],
    comments: [
      {
        name: 'Nam',
        text: 'Duis aute irure dolor in reprehenderit',
      },
      {
        name: 'Donn',
        text: 'ut labore et dolore magna aliqua',
      },
    ],
  },
  {
    uid: 5,
    id: 4,
    name: 'MSCS22',
    approved: false,
    userAvatar: require('../../assets/users/Majd.png'),
    likes: 0,
    title: 'totam rem aperiam',
    text: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium',
    category: 'Machine Learning',
    timestamp: '4.26.2023',
    tags: ['cool', 'tech', 'crazy'],
    comments: [],
  },
  {
    uid: 6,
    id: 5,
    name: 'mevcaus',
    approved: false,
    userAvatar: require('../../assets/users/Mev.png'),
    likes: 3,
    title: 'At vero eos et accusamus',
    text: 'ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos',
    category: 'Virtual Reality',
    timestamp: '4.26.2023',
    tags: ['cool', 'tech', 'crazy'],
    comments: [],
  },
  {
    uid: 7,
    id: 6,
    name: 'nnguye47',
    approved: false,
    userAvatar: require('../../assets/users/Nam.png'),
    likes: 3,
    title: 'At vero eos et accusamus',
    text: 'ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos',
    category: 'Virtual Reality',
    timestamp: '4.26.2023',
    tags: ['cool', 'tech', 'crazy'],
    comments: [],
  },
  {
    uid: 8,
    id: 7,
    name: 'mevcaus',
    approved: false,
    userAvatar: require('../../assets/users/Mev.png'),
    likes: 4,
    title: 'At vero eos et accusamus',
    text: 'ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos',
    category: 'Virtual Reality',
    timestamp: '4.26.2023',
    tags: ['cool', 'tech', 'crazy'],
    comments: [],
  },
  {
    uid: 8,
    id: 8,
    name: 'ForeDaddy',
    approved: false,
    userAvatar: require('../../assets/users/Donn.png'),
    likes: 4,
    title: 'At vero eos et accusamus',
    text: 'ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos',
    category: 'Virtual Reality',
    timestamp: '4.26.2023',
    tags: ['cool', 'tech', 'crazy'],
    comments: [],
  },
];
